#!/usr/bin/env bash
### Usage:
###    is-up <container_ip>
### --help
###

container_ip="$1"

for c in {1..1000}; do
  TEST_GET="http://${container_ip}/"
  TEST_COMMAND="curl -X GET -o /dev/null -s -w %{response_code} ${TEST_GET}"
  RESULT=`${TEST_COMMAND}`
  if [ -n "${DEBUG}" ]; then
    echo ${RESULT}
  fi
  if [ ${RESULT} == "200" ]; then
    exit 0;
  fi
  sleep .2;
done

if [ -n "${DEBUG}" ]; then
  echo ${RESULT}
fi
echo "failed to get 200 back from ${TEST_GET}"
exit 1;
