#!/bin/bash

apt-get -y install software-properties-common python g++ make git
add-apt-repository ppa:chris-lea/node.js
apt-get update
apt-get -y install nodejs

# install docker
apt-get -y install linux-image-extra-`uname -r`
sh -c "wget -qO- https://get.docker.io/gpg | apt-key add -"
sh -c "echo deb http://get.docker.io/ubuntu docker main\
> /etc/apt/sources.list.d/docker.list"
apt-get -y update
apt-get -y install lxc-docker
